/*
 
    ViewDelegate.h
    Generated by: Kian Marvi
 
    Description: This class is derived from the Apple's sample code "Learn Metal with C++" on how to create a view delegate
                 using their C++ wrapper for MetalKit within their metal-cpp-extensions folder


    Copyright [2022] [Apple Inc]

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

*/

#ifndef VIEW_DELEGATE_H
#define VIEW_DELEGATE_H
#include <MetalKit/MetalKit.hpp>

namespace MTL
{
    class Device;
}

class MetalRenderer;

class ViewDelegate : public MTK::ViewDelegate
{
    public:
        ViewDelegate( MTL::Device* metalDevice );
        virtual ~ViewDelegate() override;
        virtual void drawInMTKView( MTK::View* view ) override;

    private:
        MetalRenderer* metalRenderer;
};

#endif
