/*
 
    MacApplication.h
    Generated by: Kian Marvi
 
    Description: This class is derived from the Apple's sample code "Learn Metal with C++" on how to create an application
                 and its properties using their C++ wrapper for AppKit under the metal-cpp-extensions folder


    Copyright [2022] [Apple Inc]

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

*/

#ifndef METALAPPLICATION_H
#define METALAPPLICATION_H
#include <AppKit/AppKit.hpp>

#ifdef DEBUG
    #include <Editor/Editor.h>
#endif

namespace MTK
{
    class View;
}

class ViewDelegate;

class MacApplication : public NS::ApplicationDelegate
{
    public:
        ~MacApplication();

        NS::Menu* createMenuBar();

        virtual void applicationWillFinishLaunching( NS::Notification* notification ) override;
        virtual void applicationDidFinishLaunching( NS::Notification* notification ) override;
        virtual bool applicationShouldTerminateAfterLastWindowClosed( NS::Application* sender ) override;

    private:
        NS::Window* appWindow;
        MTK::View* metalKitView;
        ViewDelegate* viewDelegate = nullptr;
    
#ifdef DEBUG
    Editor editor;
#endif
};

#endif
